external_components:
  - source:
      type: git
      url: https://github.com/nithino/Megmeet-Lloyd-ESPHome-HVAC
      ref: main
    components:
      - megmeet_uart

logger:
  level: DEBUG

uart:
  id: uart_bus
  tx_pin: GPIO20
  rx_pin: GPIO21
  baud_rate: 9600
  parity: EVEN

sensor:
  - platform: megmeet_uart
